### ISSUE TITLE
Windows executable doesn't start

### ISSUE THREAD

**Issue by mikycampo73** [imirzov/ccx_cae#1]
Traceback (most recent call last):
  File "ccx_cae.py", line 16, in <module>
  File "c:\users\ihor\appdata\local\proyInstaller\loader\pyimod03_importers.py" line 
  File "site-packages\PyQt5\__init__.py 
  File "site-packages\PyQt5\__init__.py
ImportError: unable to find Qt5Core.dll on PATH
[8988] Failed to execute script ccx_cae

![image](https://user-images.githubusercontent.com/54395536/63500482-38639900-c4ca-11e9-9252-395d438c2496.png)

**Comment by imirzov** [comment]
Thank you for testing it on Windows! I had this bug long time ago and have expected it to be solved. It's PyInstaller bug. So I've added code appending sys._MEIPASS to the system's PATH according to [this solution](https://stackoverflow.com/questions/56949297/how-to-fix-importerror-unable-to-find-qt5core-dll-on-path-after-pyinstaller-b).

Please, check [new binaries](https://github.com/imirzov/ccx_cae/releases/edit/v0.3).

If it will not help, try to use source code with Python3 instead of binaries. Refer to [project's readme](https://github.com/imirzov/ccx_cae#for-developers).

**Comment by imirzov** [comment]
Qt5Core.dll is present in the archive.

**Comment by imirzov** [comment]
Well, I've fixed a few bus regarding absolute and relative pathes in Windows and Linux.
Please, test new binaries:
ccx_cae_ubuntu_20190822_2.zip
ccx_cae_windows_20190822_2.zip
